language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.0.3
    # For Google Maps API v1
    - addon-google_apis-google-17

script:
    - ./gradlew assembleDebug -PdisablePreDex
